os: osx
language: objective-c
osx_image: xcode11.3

cache:
  directories:
  - vendor/bundle
  - "$HOME/.pub-cache"

before_install:
  - echo $TRAVIS_OS_NAME
  - echo ${HOME}
  - echo ${TRAVIS_BUILD_DIR}
  - brew update
  - brew install --HEAD usbmuxd
  - brew unlink usbmuxd
  - brew link usbmuxd
  - brew install --HEAD libimobiledevice
  - brew install ideviceinstaller
  - brew install ios-deploy
  - gem install fastlane
  - gem install cocoapods
  - git clone https://github.com/flutter/flutter.git -b stable --depth 1 ${HOME}/flutter
  - cd cruzall
  - ${HOME}/flutter/bin/flutter doctor -v
  - ${HOME}/flutter/bin/flutter packages get
  - cd ios
  - pod repo update
  - cd ../..

before_script:
  - openssl aes-256-cbc -k $CERTIFICATE_PASSWORD -in fastlane/Certificates/distribution.p12.enc -d -a -out fastlane/Certificates/distribution.p12
  - openssl aes-256-cbc -k $CERTIFICATE_PASSWORD -in fastlane_session.enc -d -a -out fastlane_session
  - export FASTLANE_SESSION=`cat fastlane_session`

script:
  - cd cruzall
  - ${HOME}/flutter/bin/flutter test
  - ${HOME}/flutter/bin/flutter -v build ios --release --no-codesign
  - cd ..
  - fastlane submit_testflight

after_success:
  - md5sum ./Cruzall.ipa
  - echo "success"

after_failure:
  - echo "failure"

env:
  global:
  - secure: YKH9Of7KtundxxY5UzfFRpPW/NViNLUWN1ZeYpQxcpkyfBNu7aTku7gpjVd816huvcITY4eOEKQ0tDuyxauE0V6huLmvgZuYRNek3+7jFUJ1drv8Su6+RSyNtrnV7V1d94/bx4wwp92lA5JDN8yYqbVHmjs4ffFFpk0qZiD8e0tdh5KOP6T4sGz4BBNUgowy1lzB72Bh8zVT/KnytMVQLH9DNk9fLADQQprxbq8bJHtWAQnRV8B7hSGQTkzfQcqXPVN8/3BADLZNQG/2dbt5MfE73D+qES2LUj5yYhICkFE3iAVuq2wtdirE6KVDTqj/VkuxI+PCgVzPKRu/sasict44qy500bbwQxVu4h9XO69mnThA0n7keDTO2UJ05O1e/xcRvuUuONVYYqycPrC1OpNpHya5rXccU5gVTGQ9d6lzXGR59CJ+VhAriPFvOIws/zGGTANJSV5mEQQ8XFMmHLY/P/i5uxqhpWTgRnxHmYmCYUrsa0MAX0z2fx2A3JVHheImGxJn0z3qXIu940UwPxF9X+f5RtgCo7iYHM/M8iaGWqQtnMk/Iji03ivHLBhROFyyY/ZtBMLlRlTNvU33NJ4fRN4z1DeFmiBLHubxa4FxCR2LTOtSirnwBj6OBS0DEIGJTRmrNGHCWIn/5bpj/fjVCKJcIRat0cF7wF2m440=
  - secure: q9xPtxnH9QXEdJfJtaqnGjIrnXdsFYh5Tzd8owC8SaEaF/9mTV/W0P70/f3tZCUKQQ739yav6ZBPZg+nGTNzz/J9pNumJpL6wnnRCYv+MEn5f76vEtq4VRubRnaY+OVYJ5KOpwx7pCGWyj/dQUh8Wyl7JKA9sz0i/Vi9lQAPgxPrWS274DRhNil7gWg/hGk99E9ZiIiJP3sKibjlz9TxqXMUMWLRTdO9Ad4xmEDSKvT+xKMvXCNkZTUnWfbQap2mT4/9n11l9GpcOLb7GZ2/w1lPW9aIfdfbZKh5r7E5Cw0T40rl/kVJVCnaf3xps+EB7pdEhB4kXHAAjsWwWpwnZ8fUqyGAJhtvZ+5peY1nnoZH/CLWGbMT2ZfqMxRXbitBbXHo301+l9qB+tGgMNe+IhC2qCDYD6decFzXyYhsafRwJJNhl2zPgpCgT732zMSUL1rr9WAphpAEv7rfiYGNhVBJbjxudH8/rhtUC9gQm2g9draG2y/AQsFKrH65Af5rDcAPVSwizWdhGPXl0scfwxd6/3Cfbi9E5VvCQ/dtYWi5CLr8C/V9VKQiSgvXvQdZHVH35qabm5mT9j7fhAqMqHMoHuJIEYy48ZrBzQeMBUtVc5n6MzU/DTztcRfP6N+I9HPCrRPpgrX6S4ZMw5NR+Ivuej+pXOAIVHepvphzgYI=
  - secure: xXq3uOS+fLaIoD2V2qCN3HdaTujRoEqYgGJVXdp9PPeZRH+kZsl1jFrBkXTZ1abNycyxYR4qRsfixfOGjAw+NxBpRbC5RpgDMrDMU6cO3mkXxnudRYwkRpoFY1JanQCxciy/vKzvJJGJ+NaeD5VY/vf+eV2gy3q558MJFQWSjDHiqEpScOFTObRf5HdsiCXojKDKCNqWH0gjDWNvkTbusuzJUgM8yc18TKwbkbM5SwCwg8vyAG9WvB8DayViUYJNzht9dbpDaHZoTvvspZrOVZ2l/wAVeDFiCfHqFPlH6dr1Km1HCQSQAqmZ8/5t+j2um+tiSPF7UzghFYaivS6qSjsut9H3xtc3cPIZwYM89u/pV48P0KoQM/R70Szve54pyhsiVvUC+kIlEo5cdAXtx4h1yXoX+07N5dM0dIfwtkW8qazXGds9M1zwIjpNxOsSbb4pQgUmqvfVOdhUdlBk/bO79algQj9qbMP1/cNN7ubC7r03y1FMGYdQz5UXOr2F2xPMUjMHZSKfOigiaHFQhf3JjgGqvNPdy2GaKIcZwgbUM9HUr5DjPow2EXsXTuh2II1QjBWThmf2Ex5/TJjUudNaQNSvn6bMP4QTBrQtPuTO8+/Gsnd2DyGT5ePMrJAPUkHom1owWJhlJ/8g/KzxZ2UzPKqNMWM4/nNgk4jqVfE=
  - secure: gwtQULHlytBscsZxIwuVBPuFnuMNWl/NW2JKW0UAMTF/v+i4zEN1nEVGz9nz3cJj4tINjzpg76XhxATGgua7YZ8XGTMCp++hYAzq533TfChTyj8CbkLGO08FJRrwQhHORPVdGhisclLw/Aj+d9he0XBqzeM8jt/mycIfJSHbGPkT+Wn5eQYK05cabngc4cZlm1V89ojNForThK5MIypHd7Nlqr2MQsLw2nanMIdfEl9ZgS5ZcT0ZLwZfn7CCE9ErSh43L87ZiktsAN+FtDNf1EeNqDusLZO+E0XFkFw00fqR4HilZviw+q4uBm/bLn2p9/0TWH/ETkhco8VprBTbz+R3kv40/yEToD6idv1aH5ptFH8DZY6Jt6to3v2pw495EEfsbRIdzM1B7ka7sPSKZxs0Kjh1C0lSyjuaRX4CRr0b8uE2EjyMBLcx374W/pA/xfPnr/ewdtJUH2GE9EUeEUyaZjrfT4iCpsrD5ysB5cZ1tyU8JiZa4mx6dXlzdbxPUsxub6/Y1UC0otG/KjRhCxtekuTVgzpJK79TUZmhzQngyhkIftm68ImTp86DylRQt1OZaQo5+iZL8fh+vjdYGj2ADdx1utq8MeWZjKsK5IPPpctZBeb8Wj8oobsogPvBqvVqvKmVrxc/IOo/BeH6BlHuLMLyC6/v5TxAC9ErSqo=
